sudo: required

before_install:
  - mkdir "${HOME}/bin"
  - wget 'https://releases.hashicorp.com/terraform/0.8.7/terraform_0.8.7_linux_amd64.zip' -O terraform.zip
  - unzip terraform.zip
  - chmod +x terraform
  - mv terraform "${HOME}/bin/terraform"

script:
  terraform validate

notifications:
  email: false
